[global]
listen-addr = 0.0.0.0
port = 1701
access control = no

[lns default]
ip range = 10.0.2.2-10.0.2.254
local ip = 10.0.2.1
require chap = yes
refuse pap = no
require authentication = yes
name = tunnel-server
ppp debug = yes
pppoptfile = /opt/tunnel-server/configs/l2tp/options.xl2tpd
length bit = yes
